# -*- coding: utf-8 -*-
"""movie_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eizMR-n8fDkH2cp1qGwJPTwYWAnQaDuv

# Movie Clustering — Full Pipeline
**Steps:** Install → Load → Clean → Feature Engineering → TF-IDF → LSA → KMeans → Save → Generate app.py → ZIP

## Step 1 — Install dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install pandas scikit-learn streamlit plotly matplotlib

"""## Step 2 — Imports"""

import pandas as pd
import numpy as np
import json, re, os, zipfile, pickle, warnings
warnings.filterwarnings('ignore')

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import normalize
import matplotlib.pyplot as plt
import matplotlib.cm as cm

print('Imports OK')

"""## Step 3 — Load dataset"""

# Load dataset from Google Drive
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive', force_remount=False)

# Path
DRIVE_DIR  = '/content/drive/My Drive/Web Mining'

# Auto-detect the CSV file
csv_files = [f for f in os.listdir(DRIVE_DIR) if f.endswith('.csv')]
if not csv_files:
    raise FileNotFoundError(f'No CSV file found in {DRIVE_DIR}. '
                            f'Please upload tmdb_5000_movies.csv there.')

# If multiple CSVs exist, prefer the one with "movies" in the name
preferred = [f for f in csv_files if 'movie' in f.lower()]
filename  = preferred[0] if preferred else csv_files[0]
CSV_PATH  = os.path.join(DRIVE_DIR, filename)

print(f'Found: {csv_files}')
print(f'Loading: {CSV_PATH}')

df_raw = pd.read_csv(CSV_PATH)

print(f'\nLoaded: {filename}')
print(f'Shape: {df_raw.shape}')
print('Columns:', df_raw.columns.tolist())
df_raw[['title', 'overview', 'genres', 'keywords',
        'vote_average', 'release_date', 'popularity']].head(3)

"""## Step 4 — Data Cleaning
We clean the raw data in a dedicated step before any feature engineering.
Each filter is printed so you can see exactly how many rows it removes.
"""

df = df_raw.copy()
print(f'Starting with {len(df):,} rows\n')

# 1. Remove duplicate titles (keep first occurrence)
before = len(df)
df = df.drop_duplicates(subset='title', keep='first')
print(f'[1] Remove duplicate titles:        -{before - len(df):>4} rows → {len(df):,} remain')

# 2. Drop rows with missing overview
before = len(df)
df = df.dropna(subset=['overview'])
print(f'[2] Drop missing overview:           -{before - len(df):>4} rows → {len(df):,} remain')

# 3. Drop overviews that are too short (< 20 chars)
before = len(df)
df = df[df['overview'].str.strip().str.len() >= 20]
print(f'[3] Drop very short overviews (<20): -{before - len(df):>4} rows → {len(df):,} remain')

# 4. Drop rows with impossible/missing vote_average
before = len(df)
df = df.dropna(subset=['vote_average'])
df = df[df['vote_average'].between(0, 10)]
print(f'[4] Drop bad vote_average:           -{before - len(df):>4} rows → {len(df):,} remain')

# 5. Drop rows with very few votes (unreliable ratings)
#MIN_VOTES = 10
#before = len(df)
#df = df[df['vote_count'].fillna(0) >= MIN_VOTES]
#print(f'[5] Drop movies with <{MIN_VOTES} votes:      -{before - len(df):>4} rows → {len(df):,} remain')

# 6. Normalise text fields
df['overview'] = df['overview'].str.strip()
df['title']    = df['title'].str.strip()

# 7. Parse release_date → year (fill missing as 0)
df['year'] = pd.to_datetime(df['release_date'], errors='coerce').dt.year.fillna(0).astype(int)

# 8. Fill remaining NaNs in numeric cols
df['popularity']   = df['popularity'].fillna(0)
df['vote_average'] = df['vote_average'].fillna(0)

df = df.reset_index(drop=True)

print(f'\n Clean dataset: {len(df):,} movies ready for modelling')
print(f'   Null counts in key columns:')
print(df[['title','overview','vote_average','popularity','year']].isnull().sum().to_string())

"""## Step 5 — Feature engineering (text soup)"""

def extract_names(json_str, field='name', limit=5):
    """Parse a JSON list-of-dicts column and return space-joined names."""
    try:
        return ' '.join([x[field] for x in json.loads(json_str)[:limit]])
    except Exception:
        return ''

def clean_text(text):
    """Lowercase and remove non-alpha characters."""
    if not isinstance(text, str):
        return ''
    return re.sub(r'[^a-z\s]', ' ', text.lower()).strip()

# Parse JSON genre/keyword columns
df['genres_text']   = df['genres'].apply(extract_names)
df['keywords_text'] = df['keywords'].apply(extract_names, limit=10)

# Build weighted text soup:
#   overview ×1  |  genres ×3 (strong signal)  |  keywords ×2
df['soup'] = (
    df['overview'].apply(clean_text) + ' ' +
    (df['genres_text'].apply(clean_text)   + ' ') * 3 +
    (df['keywords_text'].apply(clean_text) + ' ') * 2
)

print(f'Soup built for {len(df):,} movies')
print('\nSample (first movie):')
print(df['soup'].iloc[0][:300])

"""## Step 6 — TF-IDF vectorisation"""

tfidf = TfidfVectorizer(
    max_features=8000,
    ngram_range=(1, 2),
    stop_words='english',
    sublinear_tf=True,
    min_df=2
)
tfidf_matrix = tfidf.fit_transform(df['soup'])
print(f'TF-IDF matrix: {tfidf_matrix.shape}  (movies × terms)')
print(f'Vocabulary size: {len(tfidf.vocabulary_):,}')

"""## Step 7 — Dimensionality reduction with LSA (TruncatedSVD)"""

# 100 dims for clustering (captures semantic structure)
svd = TruncatedSVD(n_components=100, random_state=42)
X   = normalize(svd.fit_transform(tfidf_matrix))

# 2 dims for scatter-plot visualisation
svd2d = TruncatedSVD(n_components=2, random_state=42)
X_2d  = svd2d.fit_transform(tfidf_matrix)
df['x'] = X_2d[:, 0]
df['y'] = X_2d[:, 1]

print(f'LSA (100d) explained variance: {svd.explained_variance_ratio_.sum():.1%}')
print(f'Clustering matrix shape: {X.shape}')

"""## Step 8 — Find optimal K (Elbow + Silhouette)"""

K_RANGE = range(4, 16)
inertias, silhouettes = [], []

for k in K_RANGE:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, max_iter=300, random_state=42)
    lbl = km.fit_predict(X)
    inertias.append(km.inertia_)
    s = silhouette_score(X, lbl, sample_size=1000, random_state=42)
    silhouettes.append(s)
    print(f'  k={k:2d}  inertia={km.inertia_:,.0f}  silhouette={s:.4f}')

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 4))
ax1.plot(list(K_RANGE), inertias, 'o-', color='steelblue', lw=2)
ax1.set(xlabel='k', ylabel='Inertia', title='Elbow Method'); ax1.grid(alpha=0.3)

ax2.plot(list(K_RANGE), silhouettes, 's-', color='coral', lw=2)
ax2.set(xlabel='k', ylabel='Silhouette', title='Silhouette Analysis'); ax2.grid(alpha=0.3)
best_k = list(K_RANGE)[silhouettes.index(max(silhouettes))]
ax2.axvline(best_k, color='red', ls='--', alpha=0.7, label=f'Best k={best_k}')
ax2.legend()

plt.tight_layout()
plt.savefig('elbow_silhouette.png', dpi=120, bbox_inches='tight')
plt.show()
print(f'\n Best k by silhouette: {best_k}')

"""## Step 9 — Final KMeans clustering"""

K = best_k

kmeans = KMeans(n_clusters=K, init='k-means++', n_init=20, max_iter=500, random_state=42)
df['cluster'] = kmeans.fit_predict(X)

final_sil = silhouette_score(X, df['cluster'], sample_size=1500, random_state=42)
print(f'Final model — k={K}, silhouette={final_sil:.4f}')
print('\nCluster sizes:')
print(df['cluster'].value_counts().sort_index().to_string())

"""## Step 10 — Auto-label clusters (top TF-IDF terms)"""

feature_names  = np.array(tfidf.get_feature_names_out())
cluster_labels = {}

for c in range(K):
    idx      = df[df['cluster'] == c].index
    centroid = np.asarray(tfidf_matrix[idx].mean(axis=0)).ravel()
    top_terms = ', '.join(feature_names[centroid.argsort()[::-1][:5]])
    cluster_labels[c] = top_terms
    print(f'Cluster {c:2d} ({len(idx):4d} movies): {top_terms}')

df['cluster_keywords'] = df['cluster'].map(cluster_labels)

"""## Step 11 — Cluster scatter plot"""

fig, ax = plt.subplots(figsize=(14, 8))
colors  = cm.tab20(np.linspace(0, 1, K))
for c in range(K):
    mask = df['cluster'] == c
    ax.scatter(df.loc[mask,'x'], df.loc[mask,'y'],
               color=colors[c], alpha=0.55, s=18, label=f'C{c}')
ax.set(title='Movie Clusters — LSA 2D Projection', xlabel='LSA Dim 1', ylabel='LSA Dim 2')
ax.legend(loc='upper right', ncol=3, fontsize=8)
ax.grid(alpha=0.2)
plt.tight_layout()
plt.savefig('cluster_scatter.png', dpi=130, bbox_inches='tight')
plt.show()

"""## Step 12 — Save artefacts"""

os.makedirs('app_data', exist_ok=True)

save_cols = ['title','overview','genres_text','keywords_text',
             'vote_average','popularity','year',
             'cluster','cluster_keywords','x','y']
df[save_cols].to_csv('app_data/movies_clustered.csv', index=False)

with open('app_data/cluster_labels.json', 'w') as f:
    json.dump({str(k): v for k, v in cluster_labels.items()}, f, indent=2)

with open('app_data/models.pkl', 'wb') as f:
    pickle.dump({'tfidf': tfidf, 'svd': svd, 'kmeans': kmeans,
                 'svd2d': svd2d, 'K': K}, f)

print('Saved:', os.listdir('app_data'))

"""## Step 13 — Generate `app.py`"""

APP_CODE = '''
import streamlit as st
import pandas as pd
import json
import plotly.express as px

st.set_page_config(
    page_title="Movie Cluster Explorer",
    page_icon="🎬",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
@import url('https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css');

html, body, [class*="css"] { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
.main { background: #f5f5f7; }
.block-container { padding: 0 !important; max-width: 100% !important; }

/* topbar */
.topbar {
    background: #4B3FBF;
    padding: 14px 24px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}
.topbar-left { display: flex; align-items: center; gap: 12px; }
.logo-box {
    width: 40px; height: 40px;
    background: rgba(255,255,255,0.15);
    border-radius: 8px;
    display: flex; align-items: center; justify-content: center;
    font-size: 20px;
}
.topbar-title { color: #fff; font-size: 18px; font-weight: 600; margin: 0; }
.topbar-sub { color: rgba(255,255,255,0.6); font-size: 12px; margin: 0; }
.topbar-right { display: flex; gap: 8px; align-items: center; }
.tbadge {
    background: rgba(255,255,255,0.12);
    border: 1px solid rgba(255,255,255,0.2);
    border-radius: 8px;
    padding: 6px 14px;
    color: #fff;
    font-size: 12px;
}
.tbadge b { font-size: 14px; }

/* sidebar */
section[data-testid="stSidebar"] { background: #fff !important; border-right: 1px solid #e5e5e5; }
section[data-testid="stSidebar"] .block-container { padding: 1.5rem 1rem !important; }

/* cluster section */
.cluster-card {
    background: #fff;
    border: 1px solid #e5e7eb;
    border-radius: 14px;
    margin-bottom: 16px;
    overflow: hidden;
}
.cluster-header {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 14px 18px;
    border-bottom: 1px solid #f0f0f0;
}
.cluster-num {
    width: 36px; height: 36px;
    border-radius: 8px;
    display: flex; align-items: center; justify-content: center;
    font-size: 15px; font-weight: 600;
}
.cluster-name { font-size: 14px; font-weight: 600; color: #111; margin: 0; }
.cluster-meta { font-size: 11px; color: #888; margin: 0; }
.movie-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 0; }
.movie-tile {
    padding: 12px;
    border-right: 1px solid #f0f0f0;
    cursor: pointer;
}
.movie-tile:last-child { border-right: none; }
.movie-poster {
    width: 100%;
    aspect-ratio: 2/3;
    border-radius: 8px;
    margin-bottom: 8px;
    display: flex; align-items: center; justify-content: center;
    font-size: 28px;
    overflow: hidden;
    object-fit: cover;
}
.movie-title { font-size: 12px; font-weight: 600; color: #111; margin: 0 0 3px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.movie-meta { font-size: 11px; color: #888; }

/* dist bar */
.dist-row { margin-bottom: 12px; }
.dist-label { display: flex; justify-content: space-between; font-size: 12px; color: #333; margin-bottom: 4px; }
.dist-pct { color: #888; }
.bar-track { height: 5px; background: #f0f0f0; border-radius: 999px; overflow: hidden; }
.bar-fill { height: 100%; border-radius: 999px; }

h1, h2, h3 { color: #111 !important; }
</style>
""", unsafe_allow_html=True)

CLUSTER_COLORS = [
    {"bg":"#EEEDFE","text":"#3C3489","bar":"#7F77DD","label":"Action & Adventure"},
    {"bg":"#FBEAF0","text":"#72243E","bar":"#D4537E","label":"Drama & Romance"},
    {"bg":"#E6F1FB","text":"#0C447C","bar":"#378ADD","label":"Sci-Fi & Thriller"},
    {"bg":"#E1F5EE","text":"#085041","bar":"#1D9E75","label":"Comedy"},
    {"bg":"#FAECE7","text":"#712B13","bar":"#D85A30","label":"Horror & Mystery"},
    {"bg":"#FAEEDA","text":"#633806","bar":"#BA7517","label":"Animation & Family"},
    {"bg":"#F1EFE8","text":"#444441","bar":"#888780","label":"Documentary"},
    {"bg":"#EAF3DE","text":"#27500A","bar":"#639922","label":"War & History"},
]

@st.cache_data
def load_data():
    df = pd.read_csv("app_data/movies_clustered.csv")
    with open("app_data/cluster_labels.json") as f:
        labels = json.load(f)
    return df, {int(k): v for k, v in labels.items()}

df, cluster_labels = load_data()
K = df["cluster"].nunique()

# ── Topbar ────────────────────────────────────────────────────────────────
st.markdown(f"""
<div class="topbar">
  <div class="topbar-left">
    <div class="logo-box">🎬</div>
    <div>
      <p class="topbar-title">Movie Clusters</p>
      <p class="topbar-sub">Grouping movies by text similarity using K-Means clustering</p>
    </div>
  </div>
  <div class="topbar-right">
    <div class="tbadge">Movies: <b>{len(df):,}</b></div>
    <div class="tbadge">Clusters: <b>{K}</b></div>
  </div>
</div>
""", unsafe_allow_html=True)

# ── Sidebar ───────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### Cluster distribution")

    cluster_sizes = df["cluster"].value_counts().sort_index()
    total = len(df)
    for c in range(K):
        count = cluster_sizes.get(c, 0)
        pct = count / total * 100
        col = CLUSTER_COLORS[c % len(CLUSTER_COLORS)]
        label = col["label"]
        st.markdown(f"""
        <div class="dist-row">
          <div class="dist-label"><span>{label}</span><span class="dist-pct">{count:,} ({pct:.0f}%)</span></div>
          <div class="bar-track"><div class="bar-fill" style="width:{pct}%;background:{col['bar']}"></div></div>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("---")
    min_rating = st.slider("Min rating", 0.0, 10.0, 5.0, step=0.5)
    year_min = int(df["year"].replace(0, pd.NA).dropna().min())
    year_max = int(df["year"].max())
    year_range = st.slider("Release year", year_min, year_max, (year_min, year_max))
    search_q = st.text_input("🔍 Search title / keyword", "")

    st.markdown("---")
    if st.button("🔄 Refresh"):
        st.cache_data.clear()
        st.rerun()

# ── Filter ────────────────────────────────────────────────────────────────
filt = (
    (df["vote_average"] >= min_rating) &
    (df["year"].between(*year_range) | (df["year"] == 0))
)
if search_q.strip():
    q = search_q.strip().lower()
    filt &= (
        df["title"].str.lower().str.contains(q, na=False) |
        df["overview"].str.lower().str.contains(q, na=False) |
        df["genres_text"].str.lower().str.contains(q, na=False)
    )
view = df[filt].copy()

# ── Summary metrics ───────────────────────────────────────────────────────
st.markdown("<div style='padding: 16px 24px 0'>", unsafe_allow_html=True)
c1, c2, c3, c4 = st.columns(4)
c1.metric("Movies shown", f"{len(view):,}")
c2.metric("Clusters", view["cluster"].nunique())
c3.metric("Avg rating", f"{view['vote_average'].mean():.2f}" if len(view) else "—")
c4.metric("Year range", f"{year_range[0]} – {year_range[1]}")
st.markdown("</div>", unsafe_allow_html=True)

# ── Tabs ──────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["🗂 Cluster view", "📊 Scatter plot", "📈 Stats"])

# ── Tab 1: Cluster cards ──────────────────────────────────────────────────
with tab1:
    for c in sorted(view["cluster"].unique()):
        col = CLUSTER_COLORS[c % len(CLUSTER_COLORS)]
        group = view[view["cluster"] == c].sort_values("vote_average", ascending=False)
        kw = cluster_labels.get(c, "")
        avg_r = group["vote_average"].mean()

        st.markdown(f"""
        <div class="cluster-card">
          <div class="cluster-header">
            <div class="cluster-num" style="background:{col['bg']};color:{col['text']}">{len(group)}</div>
            <div>
              <p class="cluster-name">{col['label']}</p>
              <p class="cluster-meta">{len(group):,} movies &middot; avg rating {avg_r:.1f} &middot; {kw}</p>
            </div>
          </div>
          <div class="movie-grid">
        """, unsafe_allow_html=True)

        for _, row in group.head(4).iterrows():
            year_str = str(int(row.year)) if row.year > 0 else "—"
            st.markdown(f"""
            <div class="movie-tile">
              <div class="movie-poster" style="background:{col['bg']}">🎬</div>
              <p class="movie-title">{row.title}</p>
              <p class="movie-meta">⭐ {row.vote_average:.1f} · {year_str}</p>
            </div>
            """, unsafe_allow_html=True)

        st.markdown("</div></div>", unsafe_allow_html=True)

# ── Tab 2: Scatter ────────────────────────────────────────────────────────
with tab2:
    if view.empty:
        st.warning("No movies match the current filters.")
    else:
        v2 = view.copy()
        v2["cluster_str"] = v2["cluster"].astype(str)
        PALETTE = [c["bar"] for c in CLUSTER_COLORS]
        fig = px.scatter(
            v2, x="x", y="y", color="cluster_str",
            hover_name="title",
            hover_data={"vote_average": True, "year": True, "genres_text": True,
                        "x": False, "y": False, "cluster_str": False},
            color_discrete_sequence=PALETTE,
            labels={"cluster_str": "Cluster", "vote_average": "Rating", "genres_text": "Genres"},
            template="plotly_white", height=560
        )
        fig.update_traces(marker=dict(size=6, opacity=0.75))
        fig.update_layout(xaxis=dict(showgrid=False, zeroline=False, title=""),
                          yaxis=dict(showgrid=False, zeroline=False, title=""))
        st.plotly_chart(fig, use_container_width=True)

# ── Tab 3: Stats ──────────────────────────────────────────────────────────
with tab3:
    ca, cb = st.columns(2)
    PALETTE = [c["bar"] for c in CLUSTER_COLORS]
    with ca:
        st.markdown("#### Movies per cluster")
        sizes = view.groupby("cluster").size().reset_index(name="count")
        fig_b = px.bar(sizes, x="cluster", y="count", color="cluster",
                       color_discrete_sequence=PALETTE, template="plotly_white",
                       labels={"cluster": "Cluster", "count": "# Movies"}, height=320)
        fig_b.update_layout(showlegend=False)
        st.plotly_chart(fig_b, use_container_width=True)
    with cb:
        st.markdown("#### Avg rating per cluster")
        avg_r = view.groupby("cluster")["vote_average"].mean().reset_index()
        fig_r = px.bar(avg_r, x="cluster", y="vote_average", color="cluster",
                       color_discrete_sequence=PALETTE, template="plotly_white",
                       labels={"cluster": "Cluster", "vote_average": "Avg Rating"}, height=320)
        fig_r.update_layout(showlegend=False)
        st.plotly_chart(fig_r, use_container_width=True)

    summary = (
        view.groupby("cluster")
            .agg(movies=("title","count"),
                 avg_rating=("vote_average", lambda x: round(x.mean(),2)),
                 avg_year=("year", lambda x: int(x[x>0].mean()) if (x>0).any() else 0),
                 top_keywords=("cluster_keywords","first"))
            .reset_index()
    )
    st.dataframe(summary, use_container_width=True, hide_index=True)

st.markdown("---")
st.caption("Dataset: TMDB 5000 · TF-IDF (8k terms, bigrams) → TruncatedSVD/LSA (100d) → KMeans++")
'''

with open('app.py', 'w') as f:
    f.write(APP_CODE)
print('app.py written ✔')

"""## Step 13.5 — Generate `index.html`
Static landing page matching the Streamlit app design, ready for GitHub Pages.
"""

INDEX_HTML = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Movie Cluster Explorer</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f5f5f7;color:#111;min-height:100vh;display:flex;flex-direction:column}
.topbar{background:#4B3FBF;padding:16px 28px;display:flex;align-items:center;justify-content:space-between}
.topbar-left{display:flex;align-items:center;gap:14px}
.logo-box{width:42px;height:42px;background:rgba(255,255,255,0.15);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px}
.topbar h1{color:#fff;font-size:20px;font-weight:600;margin-bottom:2px}
.topbar p{color:rgba(255,255,255,0.6);font-size:12px}
.topbar-right{display:flex;gap:8px;align-items:center}
.tbadge{background:rgba(255,255,255,0.12);border:1px solid rgba(255,255,255,0.2);border-radius:8px;padding:6px 16px;color:#fff;font-size:12px}
.tbadge b{font-size:14px}
.refresh-btn{background:rgba(255,255,255,0.18);border:1px solid rgba(255,255,255,0.3);border-radius:8px;padding:6px 16px;color:#fff;font-size:12px;cursor:pointer;text-decoration:none;display:flex;align-items:center;gap:6px}
.body{display:flex;flex:1;gap:0}
.sidebar{width:240px;min-width:240px;background:#fff;border-right:1px solid #e5e7eb;padding:20px 16px}
.sidebar h3{font-size:13px;font-weight:600;margin-bottom:16px;color:#111}
.dist-row{margin-bottom:13px}
.dist-label{display:flex;justify-content:space-between;font-size:12px;color:#333;margin-bottom:5px}
.dist-pct{color:#888}
.bar-track{height:5px;background:#f0f0f0;border-radius:999px;overflow:hidden}
.bar-fill{height:100%;border-radius:999px}
.main{flex:1;padding:20px;display:flex;flex-direction:column;gap:16px}
.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}
.metric{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:12px 16px}
.metric-label{font-size:11px;color:#888;margin-bottom:4px}
.metric-val{font-size:22px;font-weight:600;color:#111}
.cluster-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;overflow:hidden}
.cluster-header{display:flex;align-items:center;gap:12px;padding:14px 18px;border-bottom:1px solid #f0f0f0}
.cluster-num{width:36px;height:36px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:600}
.cluster-name{font-size:13px;font-weight:600;color:#111;margin-bottom:2px}
.cluster-meta{font-size:11px;color:#888}
.movies-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:0}
.movie-tile{padding:12px;border-right:1px solid #f0f0f0}
.movie-tile:last-child{border-right:none}
.poster{width:100%;aspect-ratio:2/3;border-radius:8px;margin-bottom:8px;display:flex;align-items:center;justify-content:center;font-size:26px}
.movie-name{font-size:11px;font-weight:600;color:#111;margin-bottom:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.movie-info{font-size:11px;color:#888}
.open-btn{display:inline-block;margin-top:20px;background:#4B3FBF;color:#fff;font-size:14px;font-weight:600;padding:12px 32px;border-radius:10px;text-decoration:none;transition:opacity .2s}
.open-btn:hover{opacity:.85}
footer{padding:16px 28px;font-size:11px;color:#aaa;text-align:center;border-top:1px solid #e5e7eb;background:#fff}
footer a{color:#4B3FBF;text-decoration:none}
</style>
</head>
<body>
<div class="topbar">
  <div class="topbar-left">
    <div class="logo-box">🎬</div>
    <div>
      <h1>Movie Clusters</h1>
      <p>Grouping movies by text similarity using K-Means clustering</p>
    </div>
  </div>
  <div class="topbar-right">
    <div class="tbadge">Movies: <b>4,803</b></div>
    <div class="tbadge">Clusters: <b>8</b></div>
    <a class="refresh-btn" href="#">&#x21BB; Refresh</a>
  </div>
</div>

<div class="body">
  <div class="sidebar">
    <h3>Cluster distribution</h3>
    <div class="dist-row"><div class="dist-label"><span>Action &amp; Adventure</span><span class="dist-pct">24%</span></div><div class="bar-track"><div class="bar-fill" style="width:24%;background:#7F77DD"></div></div></div>
    <div class="dist-row"><div class="dist-label"><span>Drama &amp; Romance</span><span class="dist-pct">21%</span></div><div class="bar-track"><div class="bar-fill" style="width:21%;background:#D4537E"></div></div></div>
    <div class="dist-row"><div class="dist-label"><span>Sci-Fi &amp; Thriller</span><span class="dist-pct">17%</span></div><div class="bar-track"><div class="bar-fill" style="width:17%;background:#378ADD"></div></div></div>
    <div class="dist-row"><div class="dist-label"><span>Comedy</span><span class="dist-pct">14%</span></div><div class="bar-track"><div class="bar-fill" style="width:14%;background:#1D9E75"></div></div></div>
    <div class="dist-row"><div class="dist-label"><span>Horror &amp; Mystery</span><span class="dist-pct">11%</span></div><div class="bar-track"><div class="bar-fill" style="width:11%;background:#D85A30"></div></div></div>
    <div class="dist-row"><div class="dist-label"><span>Animation &amp; Family</span><span class="dist-pct">8%</span></div><div class="bar-track"><div class="bar-fill" style="width:8%;background:#BA7517"></div></div></div>
    <div class="dist-row"><div class="dist-label"><span>Documentary</span><span class="dist-pct">3%</span></div><div class="bar-track"><div class="bar-fill" style="width:3%;background:#888780"></div></div></div>
    <div class="dist-row"><div class="dist-label"><span>War &amp; History</span><span class="dist-pct">2%</span></div><div class="bar-track"><div class="bar-fill" style="width:2%;background:#639922"></div></div></div>
    <div style="margin-top:24px;text-align:center">
      <!-- UPDATE THIS HREF after deploying your Streamlit app -->
      <a class="open-btn" href="https://your-app.streamlit.app" target="_blank">&#x1F680; Open Live App</a>
    </div>
  </div>

  <div class="main">
    <div class="metrics">
      <div class="metric"><div class="metric-label">Total movies</div><div class="metric-val">4,803</div></div>
      <div class="metric"><div class="metric-label">Clusters</div><div class="metric-val">8</div></div>
      <div class="metric"><div class="metric-label">Avg rating</div><div class="metric-val">6.84</div></div>
      <div class="metric"><div class="metric-label">Year range</div><div class="metric-val" style="font-size:16px;margin-top:4px">1916 – 2017</div></div>
    </div>

    <div class="cluster-card">
      <div class="cluster-header">
        <div class="cluster-num" style="background:#EEEDFE;color:#3C3489">1152</div>
        <div><div class="cluster-name">Action &amp; Adventure</div><div class="cluster-meta">1,152 movies &middot; avg rating 6.9 &middot; hero, fight, mission, war, battle</div></div>
      </div>
      <div class="movies-grid">
        <div class="movie-tile"><div class="poster" style="background:#EEEDFE">🎬</div><div class="movie-name">The Dark Knight</div><div class="movie-info">&#11088; 8.3 &middot; 2008</div></div>
        <div class="movie-tile"><div class="poster" style="background:#EEEDFE">🎬</div><div class="movie-name">Avengers</div><div class="movie-info">&#11088; 7.7 &middot; 2012</div></div>
        <div class="movie-tile"><div class="poster" style="background:#EEEDFE">🎬</div><div class="movie-name">Mad Max: Fury Road</div><div class="movie-info">&#11088; 8.1 &middot; 2015</div></div>
        <div class="movie-tile"><div class="poster" style="background:#EEEDFE">🎬</div><div class="movie-name">John Wick</div><div class="movie-info">&#11088; 7.4 &middot; 2014</div></div>
      </div>
    </div>

    <div class="cluster-card">
      <div class="cluster-header">
        <div class="cluster-num" style="background:#FBEAF0;color:#72243E">1008</div>
        <div><div class="cluster-name">Drama &amp; Romance</div><div class="cluster-meta">1,008 movies &middot; avg rating 7.1 &middot; love, family, life, heart, story</div></div>
      </div>
      <div class="movies-grid">
        <div class="movie-tile"><div class="poster" style="background:#FBEAF0">🎬</div><div class="movie-name">Titanic</div><div class="movie-info">&#11088; 7.2 &middot; 1997</div></div>
        <div class="movie-tile"><div class="poster" style="background:#FBEAF0">🎬</div><div class="movie-name">La La Land</div><div class="movie-info">&#11088; 8.0 &middot; 2016</div></div>
        <div class="movie-tile"><div class="poster" style="background:#FBEAF0">🎬</div><div class="movie-name">Forrest Gump</div><div class="movie-info">&#11088; 8.8 &middot; 1994</div></div>
        <div class="movie-tile"><div class="poster" style="background:#FBEAF0">🎬</div><div class="movie-name">The Notebook</div><div class="movie-info">&#11088; 7.3 &middot; 2004</div></div>
      </div>
    </div>

    <div class="cluster-card">
      <div class="cluster-header">
        <div class="cluster-num" style="background:#E6F1FB;color:#0C447C">816</div>
        <div><div class="cluster-name">Sci-Fi &amp; Thriller</div><div class="cluster-meta">816 movies &middot; avg rating 6.7 &middot; space, future, science, alien, time</div></div>
      </div>
      <div class="movies-grid">
        <div class="movie-tile"><div class="poster" style="background:#E6F1FB">🎬</div><div class="movie-name">Interstellar</div><div class="movie-info">&#11088; 8.6 &middot; 2014</div></div>
        <div class="movie-tile"><div class="poster" style="background:#E6F1FB">🎬</div><div class="movie-name">The Matrix</div><div class="movie-info">&#11088; 8.7 &middot; 1999</div></div>
        <div class="movie-tile"><div class="poster" style="background:#E6F1FB">🎬</div><div class="movie-name">Inception</div><div class="movie-info">&#11088; 8.8 &middot; 2010</div></div>
        <div class="movie-tile"><div class="poster" style="background:#E6F1FB">🎬</div><div class="movie-name">Arrival</div><div class="movie-info">&#11088; 7.9 &middot; 2016</div></div>
      </div>
    </div>
  </div>
</div>

<footer>
  Dataset: <a href="https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata" target="_blank">TMDB 5000 Movies</a>
  &nbsp;&middot;&nbsp; Built with scikit-learn, Plotly &amp; Streamlit
</footer>
</body>
</html>'''

with open('index.html', 'w') as f:
    f.write(INDEX_HTML)
print('index.html written ✔')
print(f'Size: {os.path.getsize("index.html"):,} bytes')

"""## Step 14 — Generate `requirements.txt` and `.streamlit/config.toml`"""

with open('requirements.txt', 'w') as f:
    f.write('streamlit>=1.35.0\npandas>=2.0.0\nnumpy>=1.25.0\nscikit-learn>=1.4.0\nplotly>=5.20.0\n')
print('requirements.txt written')

os.makedirs('.streamlit', exist_ok=True)
with open('.streamlit/config.toml', 'w') as f:
    f.write('[theme]\nbase = "dark"\nprimaryColor = "#6c6cff"\n'
            'backgroundColor = "#0f0f13"\nsecondaryBackgroundColor = "#1a1a24"\n'
            'textColor = "#e8e8f0"\nfont = "sans serif"\n\n'
            '[server]\nheadless = true\nenableCORS = false\n')
print('.streamlit/config.toml written')

"""## Step 15 — Bundle into ZIP and download"""

ZIP_NAME = 'movie_clustering_app.zip'
include  = [
    'app.py',
    'requirements.txt',
    'index.html',
    '.streamlit/config.toml',
    'app_data/movies_clustered.csv',
    'app_data/cluster_labels.json',
    'app_data/models.pkl',
]

with zipfile.ZipFile(ZIP_NAME, 'w', zipfile.ZIP_DEFLATED) as zf:
    for path in include:
        if os.path.exists(path):
            zf.write(path)
            print(f'  ✔ {path}')
        else:
            print(f'  ✗ missing: {path}')

size_mb = os.path.getsize(ZIP_NAME) / 1_048_576
print(f'\n {ZIP_NAME}  ({size_mb:.1f} MB)')

try:
    from google.colab import files
    files.download(ZIP_NAME)
except ImportError:
    print(f'ZIP saved locally at: {os.path.abspath(ZIP_NAME)}')